# Generated by Django 5.0.4 on 2025-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0002_order_payer_bank_name_order_payer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
