# Generated by Django 5.2 on 2026-03-07 08:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0002_ppccategoryquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcsubcategory',
            name='pointer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
