# Generated by Django 5.2 on 2026-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0003_ppcsubcategory_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppcproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
