# Generated by Django 5.2 on 2026-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0004_alter_ppcproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_scripts',
            field=models.TextField(blank=True, help_text='Paste full <script> tags here for SEO schema', null=True),
        ),
    ]
