# Generated by Django 5.2 on 2026-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0005_product_seo_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_scripts',
            field=models.TextField(blank=True, help_text='Paste full script tags here for SEO schema', null=True),
        ),
    ]
