# Generated by Django 5.2 on 2026-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0006_alter_product_seo_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_scripts',
            field=models.TextField(blank=True, help_text='Paste full script tags here for SEO schema', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_scripts',
            field=models.TextField(blank=True, help_text='Paste full script tags here for SEO schema', null=True),
        ),
    ]
