# Generated by Django 5.2 on 2026-03-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0007_category_seo_scripts_subcategory_seo_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seo_scripts',
        ),
    ]
