# Generated by Django 5.2 on 2026-03-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0008_remove_product_seo_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_scripts',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='seo_scripts',
        ),
    ]
