# Generated by Django 5.2 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0009_remove_category_seo_scripts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
