# Generated by Django 5.2 on 2025-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0011_categoryblog_tag_blog_category_subcategoryblog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
