# Generated by Django 5.2 on 2025-09-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0012_blog_meta_desc_blog_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategoryBlog',
        ),
    ]
