# Generated by Django 5.2 on 2026-07-11 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0012_vmwarerequestquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sub_heading', models.CharField(blank=True, max_length=500)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='ppc/services/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='ppc/services/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='ppc/services/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='ppc/services/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPCServiceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('primary_environment', models.CharField(choices=[('Microsoft 365', 'Microsoft 365'), ('VMware', 'VMware'), ('Hyper-V', 'Hyper-V'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Other', 'Other')], max_length=100)),
                ('need', models.CharField(choices=[('New Veeam deployment', 'New Veeam deployment'), ('Managed services for existing Veeam', 'Managed services for existing Veeam'), ('Other', 'Other')], max_length=150)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='globalwebsite.ppcservice')),
            ],
        ),
    ]
