# Generated by Django 5.2 on 2025-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0013_remove_blog_subcategory_delete_subcategoryblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/'),
        ),
    ]
