# Generated by Django 5.2 on 2026-07-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0014_ppcservice_meta_description_ppcservice_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcservice',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='ppcservice',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='ppcservice',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='ppcservice',
            name='image_4',
        ),
        migrations.AddField(
            model_name='ppcservice',
            name='intro_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PPCServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ppc/services/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='globalwebsite.ppcservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
