# Generated by Django 5.2 on 2026-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0015_remove_ppcservice_image_1_remove_ppcservice_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppcservicelead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
