# Generated by Django 5.2 on 2026-07-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0016_alter_ppcservicelead_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcservicelead',
            name='need',
        ),
        migrations.RemoveField(
            model_name='ppcservicelead',
            name='primary_environment',
        ),
        migrations.AddField(
            model_name='ppcservicelead',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PPCServiceCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('dropdown', 'Dropdown')], max_length=20)),
                ('dropdown_options', models.TextField(blank=True, help_text='Enter options separated by commas. Example: AWS, Azure, VMware')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='globalwebsite.ppcservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PPCServiceLeadAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='globalwebsite.ppcservicecustomfield')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to='globalwebsite.ppcservicelead')),
            ],
        ),
    ]
