# Generated by Django 5.2 on 2026-07-24 09:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0017_remove_ppcservicelead_need_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='globalwebsite.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='products', to='globalwebsite.series'),
        ),
    ]
