# Generated by Django 5.2 on 2025-09-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0018_alter_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryblog',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories_blog'},
        ),
    ]
