# Generated by Django 5.2 on 2025-12-22 06:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0024_ppcproduct_alter_contactmessageglobal_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcproduct',
            name='pointer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='ppcproduct',
            name='sub_heading',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
