# Generated by Django 5.2 on 2026-02-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0026_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('server_brand', models.CharField(max_length=100)),
                ('server_type', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=100)),
                ('server_model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=100)),
                ('ethernet_card', models.CharField(blank=True, max_length=100)),
                ('server_purpose', models.TextField(blank=True)),
                ('additional_requirement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerHDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('server_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdds', to='globalwebsite.buildserverrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServerOtherComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('server_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_components', to='globalwebsite.buildserverrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServerSSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('server_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='globalwebsite.buildserverrequest')),
            ],
        ),
    ]
