# Generated by Django 5.2 on 2026-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0027_buildserverrequest_serverhdd_serverothercomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildserverrequest',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
