# Generated by Django 5.2 on 2026-02-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalwebsite', '0028_alter_buildserverrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildserverrequest',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
