"""
Django settings for zcpl project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o8#vzyqkh9qwkq(m*8qxte+=4=p-l_e2zd*%tkx+i-9m7vfm=a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'globalwebsite',
    'india',
    'uae',
    'uk',
    'canada',
    'ckeditor',
    'ckeditor_uploader',
    'captcha',

]

CKEDITOR_UPLOAD_PATH = "uploads/"

# Optional: Allow all images
CKEDITOR_ALLOW_NONIMAGE_FILES = False


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': 'uploadimage,image2',
        'removePlugins': 'image',
    }
}



# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         'extraPlugins': 'uploadimage',
#         'filebrowserUploadUrl': '/ckeditor/upload/',       # ✅ Upload endpoint
#         'filebrowserUploadMethod': 'form',
#     },
# }

# CKEDITOR_UPLOAD_PATH = "uploads/blogs/"

# CKEDITOR_FILENAME_GENERATOR = "globalwebsite.utils.custom_filename"




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zcpl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'globalwebsite.context_processors.categories_context',
                

            ],
        },
    },
]

WSGI_APPLICATION = 'zcpl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'



# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # Additional directories to look for static files
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),  # Example: Custom static directory
# ]


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


LOGIN_URL = '/signin/'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'  # URL for accessing media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory to store uploaded files



# CKEDITOR_CONFIGS = {
#     "default": {
#         "toolbar": "full",
#     }
# }



# CKEDITOR_CONFIGS = {
#     "default": {
#         "toolbar": "full",
#         "extraPlugins": ",".join(["uploadimage"]),  # ✅ allow image upload
#         "removePlugins": "image",                  # remove old URL-only plugin
#     }
# }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'zacoitsolution@gmail.com'
EMAIL_HOST_PASSWORD = 'uvxe hxzp cfbh gyxy'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONTACT_RECEIVER_EMAIL = 'info@zacocomputer.com'
# CONTACT_RECEIVER_EMAIL = 'abhiraj@zacocomputer.com'


RECAPTCHA_PUBLIC_KEY = '6LfaCZMrAAAAAJxdbefcTWNIcr8x3B92YYgyFjMf'
RECAPTCHA_PRIVATE_KEY = '6LfaCZMrAAAAAFWsNm_QzfmQEt8qfBq15jtOpmQS'
# RECAPTCHA_PUBLIC_KEY = '6LcL9ZIrAAAAABqTwm1NNe6PQ63La_AIQztS4um5'
# RECAPTCHA_PRIVATE_KEY = '6LcL9ZIrAAAAAK-HCSZZ7HBKX8fuZV-RLSlbmfnO'
