# Generated by Django 5.2 on 2025-11-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Case Study Category',
                'verbose_name_plural': 'Case Study Categories',
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='casestudies.casestudycategory'),
        ),
    ]
