# Generated by Django 5.2 on 2025-11-24 14:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_casestudycategory_casestudy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='detailed_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
