# Generated by Django 5.2 on 2025-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_alter_casestudy_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
